
import {useState} from "react"
import { useNavigate } from "react-router-dom"
import {preview} from "../assets"
import { FormField,Loader } from "../components"
import {getRandomPrompt} from "../utils"

const handleSubmit=()=>{

}

const handleChange=(e)=>{

}

const handleSurpriseMe=()=>{
  
}
function CreatePost() {
  const navigate=useNavigate()
  const[form,setForms]=useState({
    name:'',
    prompt:'',
    photo:'',
  })
  const [generatingImg,setGeneratingImg]=useState(false)
  const[loading,setLoading]=useState(false);
  return (
   <section>
     <div>
      <h1 className="font-extrabold text-[#222328] text-[32px]
      ">Create</h1>
      <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">Create through a collection of imagination and visually
        stunning images generated by AI and share them with the commmunity
      </p>
    </div>
    <form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>
      <div className="flex flex-col gap-5">
        <FormField 
        labelName="Your Name"
        type="text"
        placeholder="Johhn"
        value={form.name}
        handleChange={handleChange}/>

        <FormField
        labelName="Prompt"
        type="text"
        placeholder="A plush toy robot sitting against a yellow wall"
        value={form.prompt}
        handleChange={handleSurpriseMe}
        isSurpriseMe
        
        />
      </div>
    </form>
   </section>
  )
}

export default CreatePost